HEROES = sorted([
    "Adam Warlock",
    "Angela",
    "Black Cat",
    "Black Panther",
    "Black Widow",
    "Blade",
    "Captain America",
    "Cloak & Dagger",
    "Daredevil",
    "DpsPool",
    "Dr. Strange",
    "Elsa Bloodstone",
    "Emma Frost",
    "Gambit",
    "Groot",
    "Hawkeye",
    "Hela",
    "Hulk",
    "Human Torch",
    "Invisible Woman",
    "Iron Fist",
    "Iron Man",
    "Jeff TLS",
    "Loki",
    "Luna Snow",
    "Magik",
    "Magneto",
    "Mantis",
    "Mr. Fantastic",
    "Moon Knight",
    "Namor",
    "Peni Parker",
    "Phoenix",
    "Psylocke",
    "Punisher",
    "Rocket Raccoon",
    "Rogue",
    "Scarlet Witch",
    "Spider-Man",
    "Squirrel Girl",
    "Star-Lord",
    "Storm",
    "SupportPool",
    "Tankpool",
    "Thing",
    "Thor",
    "Ultron",
    "Venom",
    "White Fox",
    "Winter Soldier",
    "Wolverine",
])

MAPS = sorted([
    "Arakko",
    "Birin T'Challa",
    "Central Park",
    "Celestial",
    "Hall of Djalia",
    "Heart of Heaven",
    "Hell's Haven",
    "Krakoa",
    "Lower Manhattan",
    "Midtown",
    "Museum of Contemplation",
    "Royal Palace",
    "Shin-Shibuya",
    "Spider-Islands",
    "Symbiotic Surface",
    "Throne of Knull",
    "Yggdrasill Path",
])

MAP_TYPES = [
    "Standard",
    "PTW",
    "Test",
]

MAP_MODES = {
    # Control
    "Hell's Haven": "Control",
    "Birin T'Challa": "Control",
    "Celestial": "Control",
    "Krakoa": "Control",
    # Escort
    "Arakko": "Escort",
    "Spider-Islands": "Escort",
    "Yggdrasill Path": "Escort",
    "Midtown": "Escort",
    "Museum of Contemplation": "Escort",
    # Hybrid
    "Central Park": "Hybrid",
    "Hall of Djalia": "Hybrid",
    "Symbiotic Surface": "Hybrid",
    "Shin-Shibuya": "Hybrid",
    "Heart of Heaven": "Hybrid",
    "Lower Manhattan": "Hybrid",
}

ATTACK_DEFENSE_MAPS = {
    map_name for map_name, mode in MAP_MODES.items() if mode in {"Escort", "Hybrid"}
}

MAP_SUBMAPS = {
    "Hell's Haven": [
        "Frozen Airfield",
        "Super-Soldier Factory",
        "Eldritch Monument",
    ],
    "Birin T'Challa": [
        "Imperial Institute of Science",
        "Stellar Spaceport",
        "Warrior Falls",
    ],
    "Royal Palace": [
        "Birnin Gardens",
        "Throne Room",
        "Open Atrium",
    ],
    "Krakoa": [
        "Carousel",
        "Grove",
        "Cradle",
    ],
    "Celestial": [
        "Codex",
        "Vault",
        "Hand",
    ],
    "Throne of Knull": [
        "Point A",
        "Point B",
        "Point C",
    ],
}

MAP_IMAGES = {
    # Main maps (competitive versions where available)
    "Arakko": "https://marvelrivalsapi.com/rivals/maps/large/map_1311.png",
    "Birin T'Challa": "https://marvelrivalsapi.com/rivals/maps/large/map_1272.png",
    "Central Park": "https://marvelrivalsapi.com/rivals/maps/large/map_1292.png",
    "Celestial": "https://marvelrivalsapi.com/rivals/maps/large/map_1318.png",
    "Hall of Djalia": "https://marvelrivalsapi.com/rivals/maps/large/map_1267.png",
    "Heart of Heaven": "https://marvelrivalsapi.com/rivals/maps/large/map_2042.png",
    "Hell's Haven": "https://marvelrivalsapi.com/rivals/maps/large/map_1288.png",
    "Krakoa": "https://marvelrivalsapi.com/rivals/maps/large/map_1310.png",
    "Midtown": "https://marvelrivalsapi.com/rivals/maps/large/map_1291.png",
    "Royal Palace": "https://marvelrivalsapi.com/rivals/maps/large/map_1236.png",
    "Shin-Shibuya": "https://marvelrivalsapi.com/rivals/maps/large/map_1230.png",
    "Spider-Islands": "https://marvelrivalsapi.com/rivals/maps/large/map_1245.png",
    "Symbiotic Surface": "https://marvelrivalsapi.com/rivals/maps/large/map_1290.png",
    "Throne of Knull": "https://marvelrivalsapi.com/rivals/maps/large/map_1320.png",
    "Yggdrasill Path": "https://marvelrivalsapi.com/rivals/maps/large/map_1231.png",
    "Museum of Contemplation": "/static/maps/museum_of_contemplation.jpg",
    "Lower Manhattan": "/static/maps/lower_manhattan.jpg",
    # Submaps
    "Frozen Airfield": "https://marvelrivalsapi.com/rivals/maps/large/map_1243.png",
    "Super-Soldier Factory": "https://marvelrivalsapi.com/rivals/maps/large/map_1244.png",
    "Eldritch Monument": "https://marvelrivalsapi.com/rivals/maps/large/map_1383.png",
    "Imperial Institute of Science": "https://marvelrivalsapi.com/rivals/maps/large/map_1162.png",
    "Stellar Spaceport": "https://marvelrivalsapi.com/rivals/maps/large/map_1161.png",
    "Warrior Falls": "https://marvelrivalsapi.com/rivals/maps/large/map_1169.png",
    "Birnin Gardens": "https://marvelrivalsapi.com/rivals/maps/large/map_1155.png",
    "Throne Room": "https://marvelrivalsapi.com/rivals/maps/large/map_1156.png",
    "Open Atrium": "https://marvelrivalsapi.com/rivals/maps/large/map_1170.png",
    "Carousel": "https://marvelrivalsapi.com/rivals/maps/large/map_1281.png",
    "Grove": "https://marvelrivalsapi.com/rivals/maps/large/map_1273.png",
    "Cradle": "https://marvelrivalsapi.com/rivals/maps/large/map_1382.png",
    "Codex": "https://marvelrivalsapi.com/rivals/maps/large/map_1294.png",
    "Vault": "https://marvelrivalsapi.com/rivals/maps/large/map_1295.png",
    "Hand": "https://marvelrivalsapi.com/rivals/maps/large/map_1296.png",
    "Point A": "https://marvelrivalsapi.com/rivals/maps/large/map_1320.png",
    "Point B": "https://marvelrivalsapi.com/rivals/maps/large/map_1320.png",
    "Point C": "https://marvelrivalsapi.com/rivals/maps/large/map_1320.png",
}

HERO_ROLES = {
    "Vanguard": sorted([
        "Angela","Captain America", "Dr. Strange", "Emma Frost", "Groot", "Hulk",
        "Magneto", "Rogue", "Peni Parker", "Tankpool", "Thing", "Thor", "Venom",
    ]),
    "Duelist": sorted([
        "Black Cat","Black Panther", "Black Widow", "Blade", "Daredevil",
        "DpsPool", "Elsa Bloodstone", "Hawkeye", "Hela",
        "Human Torch", "Iron Fist", "Iron Man", "Magik", "Moon Knight",
        "Mr. Fantastic", "Namor", "Phoenix", "Psylocke", "Punisher",
        "Scarlet Witch", "Spider-Man", "Squirrel Girl", "Star-Lord",
        "Storm", "Winter Soldier", "Wolverine",
    ]),
    "Strategist": sorted([
        "Adam Warlock", "Cloak & Dagger", "Invisible Woman", "Gambit", "Jeff TLS",
        "Loki", "Luna Snow", "Mantis", "Rocket Raccoon", "SupportPool",
        "Ultron", "White Fox",
    ]),
}

HERO_TRANSFORMATIONS = {
    "Adam Warlock": ["/heroes/transformations/adam-warlock-headbig-0.webp"],
    "Angela": ["/heroes/transformations/angela-headbig-0.webp"],
    "Black Cat": ["/heroes/transformations/black-cat-headbig-0.webp"],
    "Black Panther": ["/heroes/transformations/black-panther-headbig-0.webp"],
    "Black Widow": ["/heroes/transformations/black-widow-headbig-0.webp"],
    "Blade": ["/heroes/transformations/blade-headbig-0.webp"],
    "Captain America": ["/heroes/transformations/captain-america-headbig-0.webp"],
    "Cloak & Dagger": [
        "/heroes/transformations/cloak-dagger-headbig-0.webp",
        "/heroes/transformations/cloak-dagger-headbig-1.webp",
        "/heroes/transformations/cloak-dagger-headbig-2.webp",
    ],
    "Daredevil": ["/heroes/transformations/daredevil-headbig-0.webp"],
    "DpsPool": ["/heroes/transformations/deadpool-headbig-0.webp"],
    "Dr. Strange": ["/heroes/transformations/doctor-strange-headbig-0.webp"],
    "Elsa Bloodstone": ["/heroes/transformations/elsa-bloodstone-headbig-0.webp"],
    "Emma Frost": ["/heroes/transformations/emma-frost-headbig-0.webp"],
    "Gambit": ["/heroes/transformations/gambit-headbig-0.webp"],
    "Groot": ["/heroes/transformations/groot-headbig-0.webp"],
    "Hawkeye": ["/heroes/transformations/hawkeye-headbig-0.webp"],
    "Hela": ["/heroes/transformations/hela-headbig-0.webp"],
    "Hulk": [
        "/heroes/transformations/bruce-banner-headbig-0.webp",
        "/heroes/transformations/bruce-banner-headbig-1.webp",
        "/heroes/transformations/bruce-banner-headbig-2.webp",
        "/heroes/transformations/bruce-banner-headbig-3.webp",
    ],
    "Human Torch": ["/heroes/transformations/human-torch-headbig-0.webp"],
    "Invisible Woman": ["/heroes/transformations/invisible-woman-headbig-0.webp"],
    "Iron Fist": ["/heroes/transformations/iron-fist-headbig-0.webp"],
    "Iron Man": ["/heroes/transformations/iron-man-headbig-0.webp"],
    "Jeff TLS": ["/heroes/transformations/jeff-the-land-shark-headbig-0.webp"],
    "Loki": ["/heroes/transformations/loki-headbig-0.webp"],
    "Luna Snow": ["/heroes/transformations/luna-snow-headbig-0.webp"],
    "Magik": [
        "/heroes/transformations/magik-headbig-0.webp",
        "/heroes/transformations/magik-headbig-1.webp",
    ],
    "Magneto": ["/heroes/transformations/magneto-headbig-0.webp"],
    "Mantis": ["/heroes/transformations/mantis-headbig-0.webp"],
    "Moon Knight": ["/heroes/transformations/moon-knight-headbig-0.webp"],
    "Mr. Fantastic": ["/heroes/transformations/mister-fantastic-headbig-0.webp"],
    "Namor": ["/heroes/transformations/namor-headbig-0.webp"],
    "Peni Parker": ["/heroes/transformations/peni-parker-headbig-0.webp"],
    "Phoenix": ["/heroes/transformations/phoenix-headbig-0.webp"],
    "Psylocke": ["/heroes/transformations/psylocke-headbig-0.webp"],
    "Punisher": ["/heroes/transformations/the-punisher-headbig-0.webp"],
    "Rocket Raccoon": ["/heroes/transformations/rocket-raccoon-headbig-0.webp"],
    "Rogue": ["/heroes/transformations/rogue-headbig-0.webp"],
    "Scarlet Witch": ["/heroes/transformations/scarlet-witch-headbig-0.webp"],
    "Spider-Man": ["/heroes/transformations/spider-man-headbig-0.webp"],
    "Squirrel Girl": ["/heroes/transformations/squirrel-girl-headbig-0.webp"],
    "Star-Lord": ["/heroes/transformations/star-lord-headbig-0.webp"],
    "Storm": ["/heroes/transformations/storm-headbig-0.webp"],
    "SupportPool": ["/heroes/transformations/deadpool-headbig-0.webp"],
    "Tankpool": ["/heroes/transformations/deadpool-headbig-0.webp"],
    "Thing": ["/heroes/transformations/the-thing-headbig-0.webp"],
    "Thor": ["/heroes/transformations/thor-headbig-0.webp"],
    "Ultron": ["/heroes/transformations/ultron-headbig-0.webp"],
    "Venom": ["/heroes/transformations/venom-headbig-0.webp"],
    "White Fox": ["/heroes/transformations/white-fox-headbig-0.webp"],
    "Winter Soldier": ["/heroes/transformations/winter-soldier-headbig-0.webp"],
    "Wolverine": ["/heroes/transformations/wolverine-headbig-0.webp"],
}

SIDES = ["Attack", "Defense"]
RESULTS = ["Win", "Loss"]
FIRST_EVENTS = ["", "First Kill", "First Death"]
EVENT_TYPES = [
    "Fight Win",
    "Fight Loss",
    "First Kill",
    "First Death",
    "Ult Used",
    "Objective Taken",
    "Objective Lost",
    "Pick",
    "Death",
    "Other",
]